spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceekly?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(9hBRGBBky4x77a2BAn6mmg==)
    password: ENC(M39nzbJfjTdQb6lnIBmnBqroD4sxCHg0)
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
  mail:
    host: ENC(DFYiW/lIgV6p57/wlU0GWuiNyZ2NR6Ii)
    username: ENC(ydU1dKGFJ3oZEnyhCueCf5I7uPBue9tpQIdIH98pQlg=)
    password: ENC(l+Yvbx0jpSzJI4UYKtAMJ3MR29eh0QFxNuWYJYC/X+s=)
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
server:
  port: 8080
mail:
  fromMail:
    addr: ENC(QxDn2bReF541EVgqN2AqAhNHPyXpkfgKfrPOy+NbVYY=)