spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceekly?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(9hBRGBBky4x77a2BAn6mmg==)
    password: ENC(M39nzbJfjTdQb6lnIBmnBqroD4sxCHg0)
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
  mail:
    host: ENC(DFYiW/lIgV6p57/wlU0GWuiNyZ2NR6Ii)
    port: 465
    protocol: smtp
    username: ENC(ydU1dKGFJ3oZEnyhCueCf5I7uPBue9tpQIdIH98pQlg=)
    password: ENC(wX5LYcsdQCpIsm0od9F4x2pQuZXAG3sAmq8YFgRthXQ=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    default-encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
server:
  port: 80
mail:
  fromMail:
    addr: ENC(QxDn2bReF541EVgqN2AqAhNHPyXpkfgKfrPOy+NbVYY=)